### ISSUE TITLE
Failed to Parser Path on Windows 11

### ISSUE THREAD

**Issue by yaokai-liu** [xmake-io/xmake-idea#60]
### Xmake Version

 v2.9.6+20241030

### Operating System Version and Architecture

Windows 11 23H2 v22631.4317

### Describe Bug

After creating a new xmake project, in CLion, with a WSL, with the config,
![image](https://github.com/user-attachments/assets/b620fdb5-3745-4a31-a8d6-4c8660a7636e)

When click the "run" button, the little green triangle, the IDE alerted an IDE internal error, with details here
```
java.nio.file.InvalidPathException: Illegal character [:] in path at index 17: \\wsl$\ArchlinuxD:\Codelib\SDLDemo
	at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:224)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:130)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.withWorkDirectory(GeneralCommandLine.java:153)
	at io.xmake.utils.execute.CommandExKt.createWslProcess(CommandEx.kt:53)
	at io.xmake.utils.execute.CommandExKt.createWslProcess$default(CommandEx.kt:39)
	at io.xmake.utils.execute.CommandExKt.createProcess(CommandEx.kt:72)
	at io.xmake.utils.SystemUtils$runvInConsole$1$1.invokeSuspend(SystemUtils.kt:140)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

### Expected Behavior

On a totally user face, it is supposed to nothing to happend.

For the function here, the path resolving, it is supposed to resolve correctly.

### Project Configuration

Nop, since there's no configuration generated.

### Additional Information and Error Logs

Error message
```
java.nio.file.InvalidPathException: Illegal character [:] in path at index 17: \\wsl$\ArchlinuxD:\Codelib\SDLDemo
	at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:224)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:130)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.withWorkDirectory(GeneralCommandLine.java:153)
	at io.xmake.utils.execute.CommandExKt.createWslProcess(CommandEx.kt:53)
	at io.xmake.utils.execute.CommandExKt.createWslProcess$default(CommandEx.kt:39)
	at io.xmake.utils.execute.CommandExKt.createProcess(CommandEx.kt:72)
	at io.xmake.utils.SystemUtils$runvInConsole$1$1.invokeSuspend(SystemUtils.kt:140)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

**Comment by windchargerj** [comment]
The **Remote Directory** field should contain a **_Unix_** path.

**Comment by windchargerj** [comment]
I will add validation and error handling logic later.

**Comment by yaokai-liu** [comment]
A better way is considered to specify a new configuration for WSL, I suggest.

**Comment by windchargerj** [comment]
> A better way is considered to specify a new configuration for WSL, I suggest.

Yes, you can create a new configuration in the configuration editor later.

By the way, don't forget to **save** and **sync** the project before building. Although the plugin includes a simple upload feature, it is recommended to use tools like `rsync` instead.

**Comment by yaokai-liu** [comment]
I mean, a new UI to specify if using WSL, a new configuration UI.



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 3, 2024 23:48 PM
To: ***@***.***&gt;;
Cc: "Yaokai ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [xmake-io/xmake-idea] Failed to Parser Path on Windows 11 (Issue#60)




  
A better way is considered to specify a new configuration for WSL, I suggest.
  
Yes, you can create a new configuration in the configuration editor later.
 
By the way, don't forget to save and sync the project before building. Although the plugin includes a simple upload feature, it is recommended to use tools like rsync instead.

**Comment by windchargerj** [comment]
Thanks for your suggestions. I will consider making improvements.
